#!/usr/bin/python
# Example output from agent:
# 0 Samba_Service V=1 Connected to Samba on Depot OK
# 1 Samba_Service Bad Authentication. 
# 2 Samba_Service DOWN FIXIT!

from smb.SMBConnection import SMBConnection
import sys
import socket

def inventory_samba(info):
   
    inventory = []
    print info
    return inventory

def check_samba(item, params, info):
    print info
    return (3, "Check output not found in local checks")


check_info["samba"] = {
    'check_function':          check_samba,
    'inventory_function':      inventory_samba,
    'service_description':     'check connection to samba state',
    'has_perfdata':            False,
}
